apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testing-go-on-jenkins-ci
  janus-idp.io/tekton: testing-go-on-jenkins-ci
  backstage.io/kubernetes-id: testing-go-on-jenkins-ci
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testing-go-on-jenkins-ci
resources:
- deployment.yaml
- route.yaml
- service.yaml
