apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testing-go-on-jenkins-ci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testing-go-on-jenkins-ci 
  name: testing-go-on-jenkins-ci
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testing-go-on-jenkins-ci
    weight: 100 
