apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testing-go-on-jenkins-ci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testing-go-on-jenkins-ci 
  name: testing-go-on-jenkins-ci
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testing-go-on-jenkins-ci 
